create table public.asociados (
  id uuid not null default extensions.uuid_generate_v4 (),
  nombre text not null,
  cargo text not null,
  antiguedad bigint not null,
  dimension_id text not null,
  empresa_id uuid not null,
  constraint asociados_pkey primary key (id),
  constraint asociados_empresa_id_fkey foreign KEY (empresa_id) references empresas (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

create table public.calificaciones (
  id uuid not null default gen_random_uuid (),
  id_asociado uuid not null,
  id_empresa uuid not null,
  id_dimension bigint null,
  comportamiento text not null,
  puntaje integer null,
  fecha_evaluacion timestamp without time zone null,
  observaciones text null,
  sistemas text null,
  evidencia_url text null,
  constraint calificaciones_pkey primary key (id),
  constraint calificaciones_id_asociado_fkey foreign KEY (id_asociado) references asociados (id) on delete CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_calificaciones_id_asociado on public.calificaciones using btree (id_asociado) TABLESPACE pg_default;

create table public.empresas (
  id uuid not null default extensions.uuid_generate_v4 (),
  nombre text not null,
  tamano text not null,
  empleados_total integer not null,
  empleados_asociados jsonb null default '[]'::jsonb,
  unidades text not null,
  areas integer not null,
  sector text not null,
  created_at timestamp with time zone null default now(),
  constraint empresas_pkey primary key (id)
) TABLESPACE pg_default;

create table public.usuarios (
  id uuid not null,
  nombre text null,
  email text null,
  telefono text null,
  foto_url text null,
  creado_en timestamp with time zone null default now(),
  constraint usuarios_pkey primary key (id),
  constraint usuarios_id_fkey foreign KEY (id) references auth.users (id) on delete CASCADE
) TABLESPACE pg_default;
create table public.sistemas_asociados (
  id bigint generated by default as identity not null,
  nombre text null,
  constraint sistemas_asociados_pkey primary key (id)
) TABLESPACE pg_default;
create table public.messages (
  id uuid not null default extensions.uuid_generate_v4 (),
  user_id uuid not null,
  content text not null,
  created_at timestamp with time zone not null default now(),
  constraint messages_pkey primary key (id)
) TABLESPACE pg_default;