
final List<String> comportamientos = [
  'Soporte',
  'Reconocer',
  'Comunidad',
  'Liderazgo de Servidor',
  'Valorar',
  'Empoderar',
  'Mentalidad',
  'Estructura',
  'Reflexionar',
  'Análisis',
  'Colaborar',
  'Comprender',
  'Diseño',
  'Atribución',
  'A Prueba de Errores',
  'Propiedad',
  'Conectar',
  'Ininterrumpido',
  'Demanda',
  'Eliminar',
  'Optimizar',
  'Impacto',
  'Alinear',
  'Aclarar',
  'Comunicar',
  'Relación',
  'Medida',
  'Valor',
];